### ISSUE TITLE
[bug]BBcode helper FAQ link

### ISSUE THREAD

**Issue by ghost** [rollerozxa/gyarb#10]
Kind of a bug at least... it's hardcoded. Also, it doesn't even go to the right part of the FAQ (it goes to the smilies section, rather than the BBcode section).

If the FAQ isn't there or someone edited it out then it's essentially pointless having the link there.

A dropdown smiley inserter + post help list like ABXD's would probably be nicer to have in the future.

**Comment by rollerozxa** [comment]
I think smilies are included in "post formatting", which that whole section goes over.

**Comment by ghost** [comment]
It's still not relevant if somebody either, for whatever reason, rewrites the page... or removes the FAQ entirely, hence why hardcoding the link is a somewhat odd thing to do.

Also the actual post helper buttons look kinda ugly at least in comparison to ABXD's, honestly. Not sure if ABXD is using something like Font Arsehole though...
