### ISSUE TITLE
[suggestion]Plugin ideas

### ISSUE THREAD

**Issue by ghost** [rollerozxa/gyarb#12]
- PM threads
- Mood avatars
- Karma (similar to NSMBHD)
- Browser detection
- +1 Posts
- User nuke
- Merge/split threads
- Random forum randomiser
- Integration with Wikiozxa
- Custom username colours (this should also allow for defining the default colours)
- Sex/gender/pronouns (to appeal to a certain crowd)
- Profile comments
- RPG system
- Passkey
- Rereg/Spam Protection

Essentially anything that's not really a 'necessary feature' for every board, can be made into plugins I guess...

**Comment by ghost** [comment]
And yes I hit enter by mistake

**Comment by rollerozxa** [comment]
> Sex/gender/pronouns (to appeal to a certain crowd)

HELL YEAH LET'S ADD SEX TO CIRRUSBOARD, THE FIRST FORUM SOFTWARE WITH SEXUAL INTERCOURSE

**Comment by ghost** [comment]
> > Sex/gender/pronouns (to appeal to a certain crowd)
> 
> HELL YEAH LET'S ADD SEX TO CIRRUSBOARD, THE FIRST FORUM SOFTWARE WITH SEXUAL INTERCOURSE

OwO

**Comment by ghost** [comment]
The biggest issue with a plugin system in the current state of things is that we'd need to do something similar to ABXD when it comes to page handling if we want plugins to be able to use custom pages, at least without getting all hacky and having to put files into the root directory.

Though maybe there's some kind of Apache/nginx rewrite rules that'd work for that matter... oh speaking of which, a default nginx/apache template would be neat to include on the wiki, perhaps a .htaccess file in the distributable too. Gotta have the good old "The required libraries have not been defined." somewhere :P

**Comment by squishyneppy** [comment]
Wow this is old as shit
