### ISSUE TITLE
[very important]base64 encode ralsei plushies all over the codebase

### ISSUE THREAD

**Issue by ghost** [rollerozxa/gyarb#13]
we need to make the codebase cuter

what other way can we do it other than embedding cute images all over the code which will in turn make our board software bigger and therefore more powerful, we will be the neo geo of board softwares some day <3

**Comment by rollerozxa** [comment]
LOL ok sure

**Comment by ghost** [comment]
![image](https://github.com/Cirrusboard/Cirrusboard/assets/134328492/8bc93905-71b9-4b82-aa0f-4d1745c83cbb)

**Comment by ghost** [comment]
Okay, unrelated,but there's a typo in the FAQ.
'an' is applied only when the word after it sounds like (rather than is written like) a vowel, so it's really 'a user is being rude' rather than 'an user'. Can't think of any oddball dialect that pronounces user as 'ooze-ah'.

Also why not post the project info on Kafuka, given you're active there these days? Then again they might judge the whole thing just because 'bahahah Jamie Dignam the transphobic Nazi pedo from TERF island went near it'...
