### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by rollerozxa** [rollerozxa/gyarb#18]
Allowing for the user-accessible interface to be translated would be useful for non-English forums. I'd rather not have to maintain a separate Swedish language fork with heavy source modifications.

Source strings should be (British) English and completely transparent with the default locale to reduce the overhead. Unsure if it should use gettext or a custom JSON text format. former would be better for Weblate integration, unsure if certain LCD freehosts support it.

**Comment by ghost** [comment]
We've determined that ByetHost clones (e.g. InfinityFree, ProFreeHost) support gettext. This is a Good Thing(TM).

Now it's a matter of actually collating translations. Could always get a few people on board to look into helping out.

**Comment by rollerozxa** [comment]
The PHP gettext extension is... Irritating, to say the least. Ended up rolling with a very simple JSON source key => translation value format. Got most of the strings hooked up into the translation system and I have a script that can generate Gettext .pot templates, update .po translation files and then convert them to JSON files, so I can use Gettext tooling for translations.
