### ISSUE TITLE
[request]Password mincount is absurdly high

### ISSUE THREAD

**Issue by ghost** [rollerozxa/gyarb#6]
Couldn't it be lowered to 8 characters? 15 seems a litle extreme IMO. For reference, my own passwords are both 12 characters long...

**Comment by rollerozxa** [comment]
The NIST are idiots (typical Americans...), 8 character passwords are woefully insecure. Bitwarden recommends passwords to be at least 14-16 characters long, so a minimum of 15 characters makes sense. An easily memorisable passphrase could easily exceed that minimum ([see XKCD 936, also the inspiration to a certain someone's old username](https://xkcd.com/936/))

Personally my passwords are usually randomly generated base64-esque strings 20+ characters in length that I store in my password manager.
