### ISSUE TITLE
[suggestion]Should the config file info be moved to the DB eventually?

### ISSUE THREAD

**Issue by ghost** [rollerozxa/gyarb#7]
Other than some of the more necessary components that need to be stored there, wouldn't it make more sense to be able to alter those from the admin panel, particularly if we're planning on future-proofing the upcoming plugin system, upgradable schema and other such things from breaking?

Things like the smilies, ranksets and default theme in particular are something I want to see addable via the ACP, and writing directly to config.php feels particularly unwieldy in such a scenario. (On a note, bring back the MoTD/PORA box!)

Also, unrelatedly, I'm surprised there isn't a way of displaying PHP/MySQL errors via a togglable switch in config.php. (Something like that can stay in the config file because it's more or less the kind of thing that isn't typically going to be altered by anyone without server access, however.)

**Comment by koutowo** [comment]
Anything planned here, particularly with the upcoming plugin system? ABXD changed it around that time (and then treated the main settings as a plugin called 'main').
